version = 1

test_patterns = ["**/*_test.go"]

exclude_patterns = ["scripts/**"]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/W3-Engineers-Ltd/Radiant"]
