run:
  timeout: 5m
  skip-files:
    - generated.*

issues:
  new: true

linters:
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - gci
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nilerr
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - unparam
    - varcheck
    - whitespace
  disable:
    - errcheck

linters-settings:
  gci:
    local-prefixes: github.com/W3-Engineers-Ltd/Radiant
  goimports:
    local-prefixes: github.com/W3-Engineers-Ltd/Radiant
